version: '3'
services:
  node:
    build: 
      context: ./
      dockerfile: docker.node.Dockerfile
    ports:
      - "3000:3000" 
  db:
    build: 
      context: ./
      dockerfile: docker.db.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: playsports
      MYSQL_PASSWORD: Playsports2019
    ports:
      - 3306:3306